# https://www.appveyor.com/docs/build-environment/#build-worker-images
image: Visual Studio 2017

environment:
  some_secret:
    secure: HMr/gyn8EQUSnWEOp+V4WQ==

build: false

test_script:
  - ps: "$ENV:some_secret is 'not so secret!'"
