# https://www.appveyor.com/docs/build-environment/#build-worker-images
image: Visual Studio 2017

build: false

test_script:
  - ps: |

      # https://help.appveyor.com/discussions/problems/9599-rdp-invalid-login-credentials
      net.exe user /add wtf "Password123!" /Y
      net.exe localgroup administrators wtf /add

      Write-Host "1"
      Write-Verbose "2"
      Write-Output "3"
      Write-Warning "4"
      Write-Error "5"
      Write-Host "6"
      Write-Verbose "7"
      Write-Output "8"
      Write-Warning "9"
      Write-Error "10"
