# https://www.appveyor.com/docs/build-environment/#build-worker-images
image: Visual Studio 2017

build: false

test_script:
  - ps: '"test_script 1st PID is $ENV:PID"'
  - ps: '"test_script 2nd PID is $ENV:PID"'

deploy_script:
  - ps: '"deploy_script 1st PID is $ENV:PID"'
  - ps: '"deploy_script 2nd PID is $ENV:PID"'