# https://www.appveyor.com/docs/build-environment/#build-worker-images
image: Visual Studio 2017

environment:
  my_variable:
    slackuri: +NApmhZEk1qU/bSV8VZL02kNIoRbehJBI0vb6CB5TFc+OcSRFMyU62ZvwFplu+5aHlqAYZHsyu0gK5qXooOQVNCo+hk4aQqfghrytPKa6+I=

build: false

test_script:
  - ps: |

      Install-Module PSSlack, BuildHelpers
      Import-Module PSSlack, BuildHelpers

      Set-BuildEnvironment

      $RandomDebugInfo = Get-ChildItem ENV:BH*
      $RandomDebugInfo = "```$RandomDebugInfo```"

      New-SlackMessageAttachment -Color $_PSSlackColorMap.Red`
                           -Title 'Some alert or information for Slack!' `
                           -TitleLink https://www.youtube.com/watch?v=TmpRs7xN06Q `
                           -Text $RandomDebugInfo `
                           -Pretext 'Everything is broken' `
                           -AuthorName 'AppVeyor' `
                           -Fallback 'Your client is bad' `
                           -MarkDownFields 'text','pretext' |
    New-SlackMessage -Channel '@pscookiemonster' `
                     -IconEmoji :bomb: |
    Send-SlackMessage -Uri $ENV:slackuri
