# https://www.appveyor.com/docs/build-environment/#build-worker-images
image: Visual Studio 2017

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build: false

environment:
  debug_artifacts: '_debug'
  APPVEYOR_RDP_PASSWORD: 'Password123'

test_script:
  - ps: |

      net.exe user /add wtf "Password123!" /Y
      net.exe localgroup administrators wtf /add