# https://www.appveyor.com/docs/build-environment/#build-worker-images
image: Visual Studio 2017

build: false

environment:
  debug_artifacts: '_debug'
  APPVEYOR_RDP_PASSWORD: 'honestly, who cares if you get this'

test_script:
  - ps: |

      # RDP access
      iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

      "PSVersionTable:"
      $PSVersionTable
      "`n"
      "PSModulePath:"
      $ENV:PSModulePath -split ';'
      "`n"
      "OS:"
      Get-WMIObject win32_operatingsystem | Select Caption, Version

      $Depth = 2
      $null = mkdir "$ENV:debug_artifacts" -Force

      Get-Variable | Export-CliXml -Path "$ENV:debug_artifacts\Variables.xml" -Depth $Depth
      Get-Module | Export-CliXml -Path "$ENV:debug_artifacts\LoadedModules.xml" -Depth $Depth
      Get-Module -ListAvailable | Export-CliXml -Path "$ENV:debug_artifacts\AllModules.xml" -Depth $Depth
      Get-ChildItem "ENV:" | Export-CliXml -Path "$ENV:debug_artifacts\Env.xml" -Depth $Depth
      Get-PackageProvider | Export-CliXml -Path "$ENV:debug_artifacts\PackageProvider.xml" -Depth $Depth
      Get-PackageSource | Export-CliXml -Path "$ENV:debug_artifacts\PackageSource.xml" -Depth $Depth
      "Done gathering data"

artifacts:
  - path: "$(debug_artifacts)"
    name: "debug artifacts"
    type: Zip